//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cw2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Активность_спортсмена
    {
        [Required]
        [Display(Name = "Номер активности")]
        public int Номер_активости_ { get; set; }
        [DataType(DataType.Date)]
        [Required]
        [Display(Name = "Дата")]
        public DateTime Дата { get; set; }
        [Required]
        [Display(Name = "Местонахождение")]
        public string Местонахождение_ { get; set; }
        [Display(Name = "Деятельность")]
        [Required]
        public string Деятельность { get; set; }
        [Display(Name = "Свободный час")]
        [Required]
        public string Свободный_час { get; set; }
        [Display(Name = "ID спортсмена")]
        [Required]
        public int ID_спортсмена { get; set; }

        public virtual Спортсмены Спортсмены { get; set; }
    }
}
