//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cw2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Антидопинговые_тесты
    {
        [Display(Name = "Номер теста")]
        public int Номер_теста { get; set; }
        [Required]
        [Display(Name = "Дата проведения")]
        [DataType(DataType.Date)]
        public DateTime Дата_проведения { get; set; }

        [Display(Name = "Время хранения пробы")]
        public string Время_хранения_пробы { get; set; } = " ";
        [Display(Name = "Вскрытие пробы В")]
        public Nullable<bool> Вскрытие_пробы_B { get; set; }
        [Display(Name = "Наличие запрещенных препаратов")]
        public Nullable<bool> Наличие_запрещенных_препаратов { get; set; }
        [Display(Name = "Выявленные запрещенные препараты")]
        [Required]
        public string Выявленные_запрещенные_препараты { get; set; }
        [Display(Name = "Согласие спортсмена с результатом")]
        public Nullable<bool> Согласие_спортсмена_с_результатом { get; set; }
        [Display(Name = "ID пробы")]
        [Required]
        public int ID_пробы { get; set; }
        [Display(Name = "ID лаборанта")]
        [Required]
        public int ID_лаборанта { get; set; }


        public virtual Лаборанты Лаборанты { get; set; }
        public virtual Пробы Пробы { get; set; }
    }
}
