//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cw2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Лаборанты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Лаборанты()
        {
            this.Антидопинговые_тесты = new HashSet<Антидопинговые_тесты>();
            this.Пробы = new HashSet<Пробы>();
        }

        [Required]
        [Display(Name = "ID лаборанта")]
        public int ID_лаборанта { get; set; }
        [Required]
        [Display(Name = "Категория")]
        public string Категория { get; set; }
        [Required]
        [Display(Name = "Место работы")]
        public string Место_работы { get; set; }
        [Required]
        [Display(Name = "Стаж (в годах)")]
        public string Стаж__в_годах_ { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Антидопинговые_тесты> Антидопинговые_тесты { get; set; }
        public virtual Персональные_данные Персональные_данные { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пробы> Пробы { get; set; }
    }
}
