//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cw2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Персональные_данные
    {
        [Display(Name = "ID")]
        public int ID { get; set; }

        [Required]
        [Display(Name = "Фамилия")]
        public string Фамилия { get; set; }
        [Required]
        [Display(Name = "Имя")]
        public string Имя { get; set; }

        [Display(Name = "Отчество")]
        public string Отчество { get; set; }
        [Display(Name = "Пол")]
        public Nullable<bool> Пол { get; set; }

        [Display(Name = "Дата рождения")]
        [DataType(DataType.Date)]
        public System.DateTime Дата_рождения { get; set; }
        [Display(Name = "Номер телефона")]
        public string Номер_телефона { get; set; }
        [Required]
        [Display(Name = "Статус")]
        public string Статус { get; set; }


        public virtual Лаборанты Лаборанты { get; set; }
        public virtual Спортсмены Спортсмены { get; set; }
        public virtual Тренера Тренера { get; set; }
    }
}
