//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cw2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Пробы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пробы()
        {
            this.Антидопинговые_тесты = new HashSet<Антидопинговые_тесты>();
        }

        [Display(Name = "ID пробы")]
        public int ID_пробы { get; set; }
        [Required]
        [Display(Name = "Дата забора")]
        [DataType(DataType.Date)]
        public System.DateTime Дата_забора { get; set; }
        [Display(Name = "Вид пробы")]
        [Required]
        public string Вид_пробы { get; set; }
        [Display(Name = "Объем пробы (мл)")]
        [Required]
        public int Объем_пробы__мл_ { get; set; }
        [Display(Name = "Плотность (г/л)")]
        public Nullable<int> Плотность__г_л_ { get; set; }
        [Display(Name = "Наличие проб A и B")]
        public Nullable<bool> Наличие_проб_A_и_B { get; set; }
        [Required]
        [Display(Name = "ID спортсмена")]
        public int ID_спортсмена { get; set; }
        [Required]
        [Display(Name = "ID лаборанта")]
        public int ID_лаборанта { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Антидопинговые_тесты> Антидопинговые_тесты { get; set; }
        public virtual Лаборанты Лаборанты { get; set; }
        public virtual Спортсмены Спортсмены { get; set; }
    }
}
