//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cw2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Принимаемые_препараты
    {
        [Display(Name = "Номер назначения врачом")]
        public int Номер_назначения_врачом { get; set; }
        [Display(Name = "Медикаменты")]
        public string Медикаменты { get; set; }
        [Display(Name = "Пищевые добавки")]
        public string Пищевые_добавки { get; set; }
        [Display(Name = "Витамины")]
        public string Витамины { get; set; }
        [Display(Name = "Минералы")]
        public string Минералы { get; set; }
        [Required]
        [Display(Name = "Длительность приема")]
        public string Длительность_приема { get; set; }
        [Display(Name = "Действие назначения врача")]
        public Nullable<bool> Действие_назначения_врача { get; set; }
        [Display(Name = "ID спортсмена")]
        public int ID_спортсмена { get; set; }
        public virtual Спортсмены Спортсмены { get; set; }
    }
}
