//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cw2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Спортсмены
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Спортсмены()
        {
            this.Активность_спортсмена = new HashSet<Активность_спортсмена>();
            this.Принимаемые_препараты = new HashSet<Принимаемые_препараты>();
            this.Пробы = new HashSet<Пробы>();
        }

        [Display(Name = "ID спортсмена")]

        public int ID_спортсмена { get; set; }
        [Required]
        [Display(Name = "Вид спорта")]
        public string Вид_спорта { get; set; }
        [Display(Name = "Спортивная дисциплина")]
        public string Спортивная_дисциплина { get; set; }
        [Display(Name = "Спортивное(-ый) звание / разряд")]
        [Required]
        public string Спортивное__ый__звание___разряд { get; set; }
        [Required]
        [Display(Name = "Гражданство")]
        public string Гражданство { get; set; }
        [Display(Name = "Спортивное гражданство")]
        [Required]
        public string Спортивное_гражданство { get; set; }
        [Display(Name = "Инвалидность")]
        public Nullable<bool> Инвалидность { get; set; }
        [Display(Name = "Группа инвалидности")]
        public string Группа_инвалидности { get; set; }
        [Display(Name = "ID главного тренера")]
        public int ID_главного_тренера { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Активность_спортсмена> Активность_спортсмена { get; set; }
        public virtual Персональные_данные Персональные_данные { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Принимаемые_препараты> Принимаемые_препараты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пробы> Пробы { get; set; }
        public virtual Тренера Тренера { get; set; }
    }
}
