//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cw2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Тренера
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Тренера()
        {
            this.Спортсмены = new HashSet<Спортсмены>();
        }

        [Display(Name = "ID тренера")]
        public int ID_тренера { get; set; }
        [Display(Name = "Преподаваемый вид спорта")]
        [Required]
        public string Преподаваемый_вид_спорта { get; set; }
        [Required]
        [Display(Name = "Квалификация")]
        public string Квалификация { get; set; }
        [Display(Name = "Сертификация текущего года по антидопингу")]
        public Nullable<bool> Сертификация_текущего_года_по_антидопингу { get; set; }
        [Display(Name = "Наличие дисквалификаций")]
        public Nullable<bool> Наличие_дисквалификаций { get; set; }

        public virtual Персональные_данные Персональные_данные { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Спортсмены> Спортсмены { get; set; }
    }
}
